# Numpy Arrays

THEORY ---> python list allow mixed data types , slower in performance and lower memory efficiency
NumPy Array allow same data types only , much faster (C-language) and higher memory efficiency

- Installation of Numpy

In [111]:
!pip install numpy

- NumPy Array import 

In [112]:
import numpy as np

- Basic Array creation

In [113]:
arr = np.array([1,2,3,4])

print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4]


In [114]:
a = [1,2,3, "harsh"] 
print(a)


[1, 2, 3, 'harsh']


In [115]:
np.array(a)

array(['1', '2', '3', 'harsh'], dtype='<U21')

In [116]:
a = [1,2,3.5]
print(a)

[1, 2, 3.5]


In [117]:
np.array(a)

array([1. , 2. , 3.5])

THEORY ---> Vectors are linear while Matrices are multi-dimentionals and vector have only single brackets while matrices have multiple brackets

In [118]:
a = [[1,2,3],[4,5,6],[7,8,9]]
print(a)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [119]:
np.array(a)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

- Array generation function

In [120]:
arr = np.arange(1,11,2)  #it generates numbers between 1 to 11 with steps of 2
print(arr)

[1 3 5 7 9]


In [121]:
arr = np.zeros(5) #it gives 5 times 0
print(arr)

[0. 0. 0. 0. 0.]


In [122]:
arr = np.zeros((5,6))  #it gives 5x6 matrix with all element as 0  (5 rows and 6 columns)
print(arr)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [123]:
arr = np.ones((4,6))   #it gives 4x6 matix with all element as 1 (4 rows and 6 columns)
print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [124]:
arr = np.linspace(1,10,3)     #Return evenly spaced numbers over a specified interval. (start,stop,number of output required) eg; gives 3 number which are equally spaced between 1 and 10

print(arr)

[ 1.   5.5 10. ]


- Random generation function

In [125]:
arr = np.random.rand(10)    #it gives 10 random values between 0 and 1 and it comes under the concept of normalization
print(arr)

[0.72642359 0.51888867 0.80572746 0.17453405 0.11105308 0.38427734
 0.74887098 0.72369178 0.23638815 0.97359337]


In [126]:
arr = np.random.randn(10)   #it gives 10 random values between 3 and -3 and it comes under the concept of standardization
print(arr)

[-0.32965581 -0.21521557  0.84102645  0.47243562 -0.67388416 -0.91572807
  0.59072344  1.27926576 -2.23405741  1.5313178 ]


In [127]:
arr = np.random.randint(10,20,7)    #it gives 7 random integers between 10 and 20
print(arr)

[19 11 12 14 13 14 18]


- Array Attributes

In [128]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [129]:
arr.shape       #it gives the number of rows and columns in given matrices

(3, 3)

In [130]:
arr.size        #it gives total numbers of element in the matrices

9

In [131]:
arr.dtype       #it gives the datatype of elements in matrices

dtype('int64')

- Array Methods

In [132]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [133]:
a = arr.min()  #gives minimum value from matrices
print(a)

1


In [134]:
a = arr.max()   #gives maximum value from matrices
print(a)

9


In [135]:
a = arr.sum()   #gives sum of all the elements of an array
print(a)

45


THEORY ---> if we want any output row-wise or column-wise then for row axis=0 and for column axis=1

In [136]:
np.sum(arr, axis=0)    #it returns sum of the elements of matrix row wise

array([12, 15, 18])

In [137]:
np.sum(arr, axis=1)    #it returns sum of the elements of matrix column wise

array([ 6, 15, 24])

In [138]:
arr.mean()      # it gives mean of the elements of matrix

np.float64(5.0)

In [139]:
arr.std()    # it gives standard deviation on the elements od matrix

np.float64(2.581988897471611)

In [140]:
arr.argmax()   #it returns the index of a maximum element in the matrix

np.int64(8)

In [141]:
arr.argmin()   #it returns the index of a minimum element in the matrix

np.int64(0)

- Reshaping and Resizing

In [142]:
arr = np.arange(1,31)   #it generates numbers between 1 to 31

print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


THEORY ---> if we are reshaping something then the element count must also be same. eg; we have 30 element in above array so we can't reshape it into 5x5 matrix as 5x5 have only 25 element. But we can reshape into a matrix of 5x6 or 6x5 as they hace 30 elements.

In [143]:
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [144]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [145]:
arr = arr.reshape(5,6)     #if we assign the same array to itself then whenever we call it , it will come in that shape only(resize)

print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


- Numpy Indexing and Slicing of vectors

In [146]:
arr = np.arange(10,30)      #it generates numbers between 10 to 30

print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [147]:
arr[5]    # it returns the value at 5th index by indexing  (0,1,2,3,4,.........)  

np.int64(15)

In [148]:
arr[1:6]      # it gives the values from index 1 to index 5 of the array by slicing it. [start(inclusive) : end(exclusive): step size] ,  by default start = 0 end = last element strp size = 1 


array([11, 12, 13, 14, 15])

In [149]:
arr[:6]

array([10, 11, 12, 13, 14, 15])

In [150]:
arr[2:]

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29])

In [151]:
arr[2::2]   #it gives values of array from index 2 to last element with step size of 2 

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

- Numpy Indexing and Slicing of Matrix

In [152]:
arr = np.arange(1,31).reshape(6,5)

print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [153]:
arr[0,3]    #it returns the value at 0th row and 3rd column by indexing (by default the indexing of row and column start with 0)   [row,column]

np.int64(4)

In [154]:
arr[0,0]

np.int64(1)

In [155]:
arr[3]

array([16, 17, 18, 19, 20])

In [156]:
slice_arr = arr[0:2,1:3]     # it returns value from index 0 to 1 of row index and from index 1 to 2 of column index by slicing it. [start row : end row , start column:end column]

print(slice_arr)

[[2 3]
 [7 8]]


In [157]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [158]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [159]:
arr[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25],
       [28, 29, 30]])

In [160]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

- Boolean Indexing

In [161]:
arr = np.arange(10,31)

print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


In [162]:
bool_index = arr%2==0   #suppose we want to take all number from above array which is even number , that's why we apply this line of code here
print(bool_index)       #it returns true to all the number which satisfy above code and false to all which doesn't satisfy above code

[ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False  True]


In [163]:
arr = arr[bool_index]    #now if we again re-assign the bool_index to the array then it will return only the values which are true

print(arr)

[10 12 14 16 18 20 22 24 26 28 30]


- ARRAY OPERATION

-arithmetic operation

In [164]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [165]:
arr_sum = a1 + a2          # for addition the shape of arrays should be same

print(arr_sum)

[ 7  9 11 13 15]


In [166]:
arr_difference = a1 - a2      # for difference the shape of arrays should be same

print(arr_difference)

[-5 -5 -5 -5 -5]


In [167]:
arr_multiple = a1 * a2      # for multiply the shape of arrays should be same

print(arr_multiple)

[ 6 14 24 36 50]


In [168]:
arr_division = a1 / a2      # for division the shape of arrays should be same

print(arr_division)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [169]:
arr_floor_div = a1 // a2      # for floor division the shape of arrays should be same

print(arr_floor_div)

[0 0 0 0 0]


In [170]:
arr_power = a1 ** a2      # for power operation the shape of arrays should be same

print(arr_power)

[      1     128    6561  262144 9765625]


- Broadcating

THEORY ---> We can't perform arithmetic operation directly with each element of a list at a time. So we perform broadcasting (we convert our list into an array) and then if we perform arithmetic operation it will be done with each element.

In [171]:
a = [10,20,30,40,50]        # a list 

arr = np.array(a)           # an array

In [172]:
arr + 5 

array([15, 25, 35, 45, 55])

In [173]:
arr2 = np.arange(1,26).reshape(5,5)

print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [174]:
arr2 + 5 

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

- Deep Copy and Shallow Copy

THEORY ---> Deep copy means separate copy and no changes on original data while Shallow copy means changes made will be reflected in the original data too. Whenever we are slicing any portion of an array they make their own space or location in RAM that's why they don't make any changes in original array. But if we copy the array and made changes in it then it will change the original array too.

In [175]:
a = np.arange(1,21)

print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [176]:
a_slice = a[:6]              #slicing a portion

print(a_slice)

[1 2 3 4 5 6]


In [177]:
a_slice = a_slice * 10         #broadcasting in a sliced portion

print(a_slice)

[10 20 30 40 50 60]


In [178]:
print(a)              # when we make changes in the sliced portion of an array , then it will not affect the original array , so this is called deep copy.

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [179]:
b = a       #if we copy the  original array 

b[0] = 99     #now make changes it in.

In [180]:
print(b)

[99  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [181]:
print(a)         #changes appears in the original array too

[99  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [182]:
a = np.arange(1,21)

print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [183]:
b = a.copy()       # if we assign the copy of the original array 

b[0] = 99         # now make changes it in.

In [184]:
print(b)

[99  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [185]:
print(a)       # no changes in original array because we assign copy of original array to b.

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


- Matrix Multiplication

In [186]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [187]:
print(a)

[[1 2]
 [3 4]]


In [188]:
print(b)

[[5 6]
 [7 8]]


In [189]:
a * b     # this is a multiplication based on indexing (not a matrix multiplication)

array([[ 5, 12],
       [21, 32]])

In [190]:
a @ b   # (Method 1) this is a matrix multiplication

array([[19, 22],
       [43, 50]])

In [191]:
np.dot(a,b)    # (Method 2) this is a matrix multiplication

array([[19, 22],
       [43, 50]])

- ADVANCE ARRAY MANIPULATION

-Stacking Array

THEORY ---> We can't stack into two matrices as they are already stacked . So we have to stack two vectors or array.

In [192]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [193]:
np.vstack((a,b))      # we stack a and b vertically in a single array.

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [194]:
np.hstack((a,b))    # we stack a and b horizontally in a single array.

array([1, 2, 3, 4, 5, 6, 7, 8])

In [195]:
np.column_stack((a,b))  # we stack a and b column wise in a single array. (look likes we take transpose of both a and b and stack them horizontally)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

-Splitting Array

In [196]:
a = np.arange(16).reshape(4,4)

print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [197]:
np.hsplit(a, 2)     # Split an array horizontally into multiple sub-arrays of equal size.

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [198]:
np.hsplit(a, 4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [199]:
np.vsplit(a, 2)       # Split an array vertically into multiple sub-arrays of equal size.

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [200]:
b = np.vsplit(a, 4)

In [201]:
for i in b:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]


# EXERCISE 1

- Valid Soduku

In [202]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

Solution to prove a soduku a valid soduku

In [203]:
a = np.sum(s, axis=0)   # we check whether the sum of all the elements of the each row is 45 or not (sum of all the element in each row is 45 in a valid soduku)

for i in a:
    if i != 45:
        print("this is not a valid soduku")
        break
else:
    print("currently for rows, soduku is valid")

currently for rows, soduku is valid


In [204]:
b = np.sum(s, axis=1)    # we check whether the sum of all the elements of the each column is 45 or not (sum of all the element in each column is 45 in a valid soduku)

for i in b:
    if i != 45:
        print("this is not a valid soduku")
        break
else:
    print("for columns also , soduku is valid")



for columns also , soduku is valid


In [205]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())



45
45
45
45
45
45
45
45
45


# EXERCISE 2

In [206]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [207]:
#Get the shape of the matrix.

data.shape

(5, 3)

In [208]:
#Find the average age of students.
np.mean(data[:,0])

np.float64(18.4)

In [209]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [210]:
#Find the highest Science mark.
np.max(data[:,2])

np.int64(95)

In [211]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1] > 90]   # we use boolean indexing


array([[19, 92, 88]])

In [212]:
#Increase Math marks of all students by 5.

data[:,1] += 5



In [213]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [214]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [215]:
#Find how many students are younger than 19.

# np.sum(data[:,0]<19)
len(data[data[:,0] < 19])

3

In [216]:
#Calculate the average marks in each subject (column-wise mean).

np.mean(data[:,1:] , axis= 0)

array([86.6, 83.2])

In [217]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [218]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >= 80) & (data[:,2] >= 80)]


array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [219]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2] < 75] = 0


In [220]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])